language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "nightly"
services:
  - mysql
env:
  - DJANGO_VERSION=2.0 DB=mysql
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database test;' -u root
script:
  - python manage.py test
matrix:
  fast_finish: true
  allow_failures:
    - python: 2.7
    - python: 3.5
    - python: 3.7
    - python: 3.7-dev
    - python: nightly
