# Generated by Django 2.0.4 on 2018-04-29 14:50

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('messagesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='contact',
        ),
    ]
