# Generated by Django 2.0.4 on 2018-04-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0003_auto_20180429_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='sender',
        ),
    ]
