# Generated by Django 2.0.4 on 2018-04-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0010_auto_20180429_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name=['<django.db.models.fields.related.OneToOneField>', '<django.db.models.fields.related.OneToOneField>']),
        ),
    ]
