# Generated by Django 2.0.4 on 2018-04-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0016_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
